.\" Copyright (c) 2014 Tristan Le Guern <tleguern@bouledef.eu>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt SETSID 1
.Os
.Sh NAME
.Nm setsid
.Nd invoke a command in a new session
.Sh SYNOPSIS
.Nm
.Ar utility
.Op Ar arg ...
.Sh DESCRIPTION
The
.Nm
command allows the specified utility to be run in a new
session. To do this,
.Nm
looks if it is already a session leader and calls
.Xr fork 2
if not. Then it calls
.Xr setsid 2
and executes
.Ar utility
along with any arguments.
.Sh EXIT STATUS
The
.Nm
utility exits with one of the following values:
.Pp
.Bl -tag -width Ds -offset indent -compact
.It 126
The
.Ar utility
was found but could not be invoked.
.It 127
The
.Ar utility
could not be found or an error occurred in
.Nm .
.El
.Pp
Otherwise, the exit status of
.Nm
shall be that of
.Ar utility .
.Sh SEE ALSO
.Xr nohup 1
.Xr setsid 2
.Sh AUTHORS
The
.Nm
utility was written by
.An Rick Sladkey Aq Mt jrs@world.std.com .
.Pp
The current implementation was written by
.An Tristan Le Guern Aq Mt tleguern@bouledef.eu .

